# -*- coding: utf-8 -*-
"""Uji Coba.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oe_AgAyH8s_KCBa5SfQ-7YLjpwmk_OAx
"""

pip install https://github.com/neuropsychology/neurokit/zipball/dev

import numpy as np
import pandas as pd
import neurokit2 as nk
import struct

ecg1 = nk.ecg_simulate(duration=10, sampling_rate=44100, heart_rate=70)
ecg2 = nk.ecg_simulate(duration=20, sampling_rate=44100, heart_rate=120)
ecg3 = nk.ecg_simulate(duration=30, sampling_rate=44100, heart_rate=80)

f = open('test.wav', 'wb')
for i in ecg1:
    f.write(struct.pack('b', int(i)))
for i in ecg2:
    f.write(struct.pack('b', int(i)))
for i in ecg3:
    f.write(struct.pack('b', int(i)))

f.close()